### ISSUE TITLE
spring mvc neg view jsp & html togerther

### ISSUE THREAD

**Issue by user20161119** [paulc4/mvc-content-neg-views#1]
this is not about issue,just want to request help,in my src/main/webapp/jsp/ folder,there are jsp pages,and in src/main/webapp has a lot html pages,and i want to return to html page directly,content-neg can do this?
![image](https://f.cloud.github.com/assets/123967/1223944/4b51605c-2736-11e3-8058-64e69a2e4f8a.png)
![image](https://f.cloud.github.com/assets/123967/1223946/61bdeee6-2736-11e3-84d9-bb61555aea23.png)

**Comment by paulc4** [comment]
Unfortunately the InternalResourceViewResolver defines its content-type as being HTML. The CNVR can differentiate between views that return different types of content, but not between two views that return the same type.

You might be able to write an extended InternalResourceViewResolver that looks for HTML files in one location.  and, if not found, returns the JSP page instead. No need to use the CNVR at all.

Does this help?

**Comment by paulc4** [comment]
Here is a simpler solution.

Use this configuration (no need to use content negotiation):

```
<bean id="viewResolver" class="example.SmartInternalResourceViewResolver" 
        p:prefix="/WEB-INF/jsp/" p:suffix=".jsp" p:order="1"/>

<bean id="viewResolver2" class="org.springframework.web.servlet.view.InternalResourceViewResolver" 
        p:prefix="/html/" p:suffix=".html" p:order="2"/>
```

The first resolver looks for a JSP file, the second for an HTML file.  Notice that the HTML files should go into a sub-directory (or they will get confused with controller mappings and infinite redirection loops can occur).

The SmartInternalResourceViewResolver checks to see if the JSP file exists, and returns null if not (allowing chaining).

It can be found here: https://www.dropbox.com/s/lo4w2aplsyuk9df/SmartInternalResourceViewResolver.java

**Comment by user20161119** [comment]
thanks,i use this hack:

```
<bean id="viewResolver2" class="org.springframework.web.servlet.view.InternalResourceViewResolver"   p:prefix="/" p:suffix="" />
```

and in contronller,i return like "jsp/abc.jsp" or "html/abc.html"
and your solution is better than above,thanks

**Comment by paulc4** [comment]
Just so you know: what you are doing _is_ a hack.  More importantly, it means your controller knows too much about your views.  The whole point of the MVC pattern is a separation of concerns - the controller should not need to know about whether you are using JSP, or HTML or anything else.  What you have works, so feel free to go with it, but it is not best practice.

If you are happy either way, please close this again.  I'm glad we got a solution anyway.

**Comment by user20161119** [comment]
thanks,and i need to use CNVR,i need to return json using jackson,anyway,i am going to take your advice,and implement new viewresolver.

**Comment by jiqiyoudu5** [comment]
Can you show me the SmartInternalResourceViewResolver.java code?
