### ISSUE TITLE
XML content

### ISSUE THREAD

**Issue by igler** [paulc4/mvc-content-neg-views#2]
http://localhost:8080/mvc-content-neg-views/accounts.json works but http://localhost:8080/mvc-content-neg-views/accounts.xml returns an empty page. Did I miss anything?

**Comment by igler** [comment]
OK, got it working. It seems to be an issue with the built in Eclipse/STS web browser.

**Comment by igler** [comment]
Trying to adopt you example to my scenario. The class looks like this:

<pre><code>import java.util.ArrayList;
import java.util.List;
import org.springframework.beans.factory.config.PropertyPlaceholderConfigurer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.MediaType;
import org.springframework.oxm.jaxb.Jaxb2Marshaller;
import org.springframework.web.accept.ContentNegotiationManager;
import org.springframework.web.servlet.ViewResolver;
import org.springframework.web.servlet.config.annotation.*;
import org.springframework.web.servlet.view.ContentNegotiatingViewResolver;
import org.springframework.web.servlet.view.InternalResourceViewResolver;
import org.springframework.web.servlet.view.JstlView;
import de.myApp.model.Location;
import de.myApp.services.config.ServicesConfiguration;
import de.myApp.web.view.JsonViewResolver;
import de.myApp.web.view.MarshallingXmlViewResolver;
@Configuration
@EnableWebMvc
@Import(ServicesConfiguration.class)
@ComponentScan
public class WebMvcConfiguration extends WebMvcConfigurerAdapter {
    @Override
    public void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {
    configurer.enable();
    }
    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
    registry.addViewController("/").setViewName("main");
    registry.addViewController("/documentation/api").setViewName("api-documentation");
    }
    @Bean
    public InternalResourceViewResolver internalResourceViewResolver() {
    InternalResourceViewResolver internalResourceViewResolver = new InternalResourceViewResolver();
    internalResourceViewResolver.setViewClass(JstlView.class);
    internalResourceViewResolver.setPrefix("/WEB-INF/views/");
    internalResourceViewResolver.setSuffix(".jsp");
    return internalResourceViewResolver;
    }
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/**").addResourceLocations("/");
    }
    @Bean
    public static PropertyPlaceholderConfigurer swaggerProperties() {
    final PropertyPlaceholderConfigurer swaggerProperties = new PropertyPlaceholderConfigurer();
    swaggerProperties.setLocation(new ClassPathResource("swagger.properties"));
    return swaggerProperties;
    }
    @Override
    public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
    configurer.favorPathExtension(true);
    configurer.ignoreAcceptHeader(true);
    configurer.useJaf(false);
    configurer.mediaType("xml", MediaType.APPLICATION_XML);
    configurer.mediaType("json", MediaType.APPLICATION_JSON);
    }
    @Bean
    public ViewResolver contentNegotiatingViewResolver(ContentNegotiationManager manager) {
    List<ViewResolver> resolvers = new ArrayList<ViewResolver>();
    resolvers.add(getJsonViewResolver());
    resolvers.add(getMarshallingXmlViewResolver());
    ContentNegotiatingViewResolver resolver = new ContentNegotiatingViewResolver();
    resolver.setContentNegotiationManager(manager);
    resolver.setViewResolvers(resolvers);
    return resolver;
    }
    private ViewResolver getJsonViewResolver() {
    return new JsonViewResolver();
    }
    private ViewResolver getMarshallingXmlViewResolver() {
    Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
    marshaller.setClassesToBeBound(Location.class);
    return new MarshallingXmlViewResolver(marshaller);
    }
</code></pre>

The URI http://localhost:8080/myApp/api/locations returns JSON, also http://localhost:8080/myApp/api/locations.json. But when I try http://localhost:8080/myApp/api/locations.xml I get an error:

<pre><code>2013-11-12 16:59:56,716 DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Resolving exception from handler [public java.util.List<de.myApp.model.Location> de.myApp.web.controllers.ApiController.getLocations()]: org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
2013-11-12 16:59:56,716 DEBUG org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver - Resolving exception from handler [public java.util.List<de.myApp.model.Location> de.myApp.web.controllers.ApiController.getLocations()]: org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
2013-11-12 16:59:56,716 DEBUG org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Resolving exception from handler [public java.util.List<de.myApp.model.Location> de.myApp.web.controllers.ApiController.getLocations()]: org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
2013-11-12 16:59:56,716 DEBUG org.springframework.web.servlet.DispatcherServlet - Null ModelAndView returned to DispatcherServlet with name 'appServlet': assuming HandlerAdapter completed request handling
</code></pre>

The HTTP status is: 406 
The message is: The resource identified by this request is only capable of generating responses with characteristics not acceptable according to the request "accept" headers.

Any ideas what I missed to configure/implement?

**Comment by paulc4** [comment]
Sadly, this does look OK.

Try enabling Java Activation by setting useJaf(true).  Make sure the 
activation jar is in your POM too.

On 13/11/13 3:04 AM, Michael Igler wrote:

> Trying to adopt you example to my scenario. The class looks like this:
> 
> |import java.util.ArrayList;
> import java.util.List;
> 
> import org.springframework.beans.factory.config.PropertyPlaceholderConfigurer;
> import org.springframework.context.annotation.Bean;
> import org.springframework.context.annotation.ComponentScan;
> import org.springframework.context.annotation.Configuration;
> import org.springframework.context.annotation.Import;
> import org.springframework.core.io.ClassPathResource;
> import org.springframework.http.MediaType;
> import org.springframework.oxm.jaxb.Jaxb2Marshaller;
> import org.springframework.web.accept.ContentNegotiationManager;
> import org.springframework.web.servlet.ViewResolver;
> import org.springframework.web.servlet.config.annotation.*;
> import org.springframework.web.servlet.view.ContentNegotiatingViewResolver;
> import org.springframework.web.servlet.view.InternalResourceViewResolver;
> import org.springframework.web.servlet.view.JstlView;
> 
> import de.myApp.model.Location;
> import de.myApp.services.config.ServicesConfiguration;
> import de.myApp.web.view.JsonViewResolver;
> import de.myApp.web.view.MarshallingXmlViewResolver;
> 
> @Configuration
> @EnableWebMvc
> @Import(ServicesConfiguration.class)
> @ComponentScan
> public class WebMvcConfiguration extends WebMvcConfigurerAdapter {
> 
> ```
>  @Override
>  public void configureDefaultServletHandling(DefaultServletHandlerConfigurer configurer) {
>  configurer.enable();
>  }
> 
>  @Override
>  public void addViewControllers(ViewControllerRegistry registry) {
>  registry.addViewController("/").setViewName("main");
>  registry.addViewController("/documentation/api").setViewName("api-documentation");
>  }
> 
>  @Bean
>  public InternalResourceViewResolver internalResourceViewResolver() {
>  InternalResourceViewResolver internalResourceViewResolver = new InternalResourceViewResolver();
>  internalResourceViewResolver.setViewClass(JstlView.class);
>  internalResourceViewResolver.setPrefix("/WEB-INF/views/");
>  internalResourceViewResolver.setSuffix(".jsp");
>  return internalResourceViewResolver;
>  }
> 
>  @Override
>  public void addResourceHandlers(ResourceHandlerRegistry registry) {
>  registry.addResourceHandler("/**").addResourceLocations("/");
>  }
> 
>  @Bean
>  public static PropertyPlaceholderConfigurer swaggerProperties() {
>  final PropertyPlaceholderConfigurer swaggerProperties = new PropertyPlaceholderConfigurer();
>  swaggerProperties.setLocation(new ClassPathResource("swagger.properties"));
>  return swaggerProperties;
>  }
> 
>  @Override
>  public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
>  configurer.favorPathExtension(true);
>  configurer.ignoreAcceptHeader(true);
>  configurer.useJaf(false);
>  configurer.mediaType("xml", MediaType.APPLICATION_XML);
>  configurer.mediaType("json", MediaType.APPLICATION_JSON);
>  }
> 
>  @Bean
>  public ViewResolver contentNegotiatingViewResolver(ContentNegotiationManager manager) {
>  List resolvers = new ArrayList();
>  resolvers.add(getJsonViewResolver());
>  resolvers.add(getMarshallingXmlViewResolver());
> 
>  ContentNegotiatingViewResolver resolver = new ContentNegotiatingViewResolver();
>  resolver.setContentNegotiationManager(manager);
>  resolver.setViewResolvers(resolvers);
>  return resolver;
>  }
> 
>  private ViewResolver getJsonViewResolver() {
>  return new JsonViewResolver();
>  }
> 
>  private ViewResolver getMarshallingXmlViewResolver() {
>  Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
>  marshaller.setClassesToBeBound(Location.class);
>  return new MarshallingXmlViewResolver(marshaller);
>  }
> ```
> 
> |
> |
> 
> The URI http://localhost:8080/myApp/api/locations returns JSON, also
> http://localhost:8080/myApp/api/locations.json. But when I try
> http://localhost:8080/myApp/api/locations.xml I get an error:
> 
> |2013-11-12 16:59:56,716 DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Resolving exception from handler [public java.util.List de.myApp.web.controllers.ApiController.getLocations()]: org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
> 2013-11-12 16:59:56,716 DEBUG org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver - Resolving exception from handler [public java.util.List de.myApp.web.controllers.ApiController.getLocations()]: org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
> 2013-11-12 16:59:56,716 DEBUG org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Resolving exception from handler [public java.util.List de.myApp.web.controllers.ApiController.getLocations()]: org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
> 2013-11-12 16:59:56,716 DEBUG org.springframework.web.servlet.DispatcherServlet - Null ModelAndView returned to DispatcherServlet with name 'appServlet': assuming HandlerAdapter completed request handling
> |
> 
> The HTTP status is: 406
> The message is: The resource identified by this request is only capable
> of generating responses with characteristics not acceptable according to
> the request "accept" headers.
> 
> Any ideas what I missed to configure/implement?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paulc4/mvc-content-neg-views/issues/2#issuecomment-28305971.

## 

Paul Chapman
   Senior Consultant, Pivotal
   pchapman@gopivotal.com
   +61 418 340 935 (Mobile)

**Comment by igler** [comment]
Tried that but no success.Copied your accounts class into my model to see if there is something wrong with my models. I can get JSON representation, but no XML.

**Comment by igler** [comment]
This is a working config for me:

<pre><code>@Bean
    public XStreamMarshaller xStreamMarshaller() {
        final XStreamMarshaller marshaller = new XStreamMarshaller();
        return marshaller;
    }
    
    @Bean
    public MarshallingHttpMessageConverter marshallingHttpMessageConverter() {
        final MarshallingHttpMessageConverter converter = new MarshallingHttpMessageConverter();
        converter.setMarshaller(xStreamMarshaller());
        converter.setUnmarshaller(xStreamMarshaller());
        return converter;
    }
    
    @Bean
    public MappingJacksonHttpMessageConverter mappingJacksonHttpMessageConverter() {
        final MappingJacksonHttpMessageConverter converter = new MappingJacksonHttpMessageConverter();
        return converter;
    }
    
    @Override
    public void configureMessageConverters( final List< HttpMessageConverter< ? >> converters ){
        super.configureMessageConverters( converters );
 
        converters.add(marshallingHttpMessageConverter());
        converters.add(mappingJacksonHttpMessageConverter());
    }
    
    @Bean
    public ContentNegotiatingViewResolver contentNegotiatingViewResolver(ContentNegotiationManager manager) {
        final ContentNegotiatingViewResolver resolver = new ContentNegotiatingViewResolver();
               
        manager.resolveFileExtensions(MediaType.APPLICATION_XML);
        manager.resolveFileExtensions(MediaType.APPLICATION_JSON);
        resolver.setContentNegotiationManager(manager);
        
        final List<View> defaultViews = new ArrayList<View>();
        defaultViews.add(marshallingView());
        defaultViews.add(mappingJacksonJsonView());
        
        resolver.setDefaultViews(defaultViews);
        
        final List<ViewResolver> viewResolvers = new ArrayList<ViewResolver>();
        viewResolvers.add(internalResourceViewResolver());
        resolver.setViewResolvers(viewResolvers);
        
        return resolver;
    }
    
    @Bean
    public MarshallingView marshallingView() {
        MarshallingView view = new MarshallingView(xStreamMarshaller());
        return view;    
    }
    
    @Bean
    public MappingJacksonJsonView mappingJacksonJsonView() {
        final MappingJacksonJsonView view = new MappingJacksonJsonView();
        return view;
    }
</code></pre>

… together with

<pre><code>&lt;dependency>
            &lt;groupId>com.thoughtworks.xstream&lt;/groupId>
            &lt;artifactId>xstream&lt;/artifactId>
            &lt;version>1.4.5&lt;/version>
       &lt;/dependency>
        &lt;dependency>
            &lt;groupId>org.codehaus.jackson&lt;/groupId>
            &lt;artifactId>jackson-mapper-asl&lt;/artifactId>
            &lt;version>1.9.13&lt;/version>
        &lt;/dependency>
        &lt;dependency>
            &lt;groupId>org.codehaus.jackson&lt;/groupId>
            &lt;artifactId>jackson-core-asl&lt;/artifactId>
            &lt;version>1.9.13&lt;/version>
        &lt;/dependency>
</code></pre>

**Comment by paulc4** [comment]
So it all works now?

I thought of two more possible problems:

Is the class you are trying to convert to XML annotated with JAXB annotations?  The default marshaller uses JAXB, but only if the object you put in the model has @XmlRootElement at the class level (other annotations may also be needed).

Also, the MappingJacksonJsonView converts _all_ the objects in the Model to JSON, but the MarshallingView only converts the _first_ object it finds in the Model.  Is there only one object in your model?

-Paul

**Comment by igler** [comment]
Yes, it works now. Concerning your questions: I copied your Account.class example into my project, adjusted the repository services and api-controller but no success. My currently configuration uses XStream which I Import through pom. If I switch to JAXB configuration then I get the old error:

<pre><code>@Bean
    public Jaxb2Marshaller jaxb2Marshaller() {
    final Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
    marshaller.setClassesToBeBound(EmonsLocation.class);
    return marshaller;
    }
    @Bean
    public MarshallingHttpMessageConverter marshallingHttpMessageConverter() {
    final MarshallingHttpMessageConverter converter = new MarshallingHttpMessageConverter();
    converter.setMarshaller(jaxb2Marshaller());
    converter.setUnmarshaller(jaxb2Marshaller());
    return converter;
    }
</code></pre>

It is really confusing as I do not get any ClassNotFoundErrors about JAXB. So I assume it is included somewhere and can be found at runtime.

**Comment by jiqiyoudu5** [comment]
Can you show me the SmartInternalResourceViewResolver.java code?

**Comment by paulc4** [comment]
The `ContentNegotiatingViewResolver` _is_ the "smart" view resolver.
